build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related prod APIs "
  contactDetails:
    name: "Tanver Ahammed - Product Owner"
    email: "tanver@mss.com"
  onCallSupport:
    - 01XXXXXXXXXXX
    - 01XXXXXXXXXXX