spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to MSS cards related QA APIs "
  contactDetails:
    name: "Aminul Bari - QA Lead"
    email: "aminul@mss.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267