spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to MSS Bank cards related prod APIs "
  contactDetails:
    name: "Tanver Ahammed - Product Owner"
    email: "tanver@mss.com"
  onCallSupport:
    - 01XXXXXXXXXX
    - 01XXXXXXYYYX