build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "Tanver Ahammed - Developer"
    email: "tanver@mss.com"
  onCallSupport:
    - 01XXXXXXXXXX
    - 01XXXXXXXXXX