server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    # active: native # server & file
    active: git # git
  cloud:
    config:
      server:
        # native:
        # search-locations: "classpath:/config"    # using inside config server resource
        # search-locations: "file:///home/tanver/Documents/Code/Microservices/NEW-Master-Microservices-with-Spring-Boot-Docker-Kubernetes/config"    # using file system
        git:
          uri: "https://github.com/Tanver-Ahammed/mss-config.git"
          default-label: "main"
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"