build:
  version: "1.0"

accounts:
  message: "Welcome to MssBank accounts related prod APIs "
  contactDetails:
    name: "Tanver Ahammed - Product Owner"
    email: "tanver@mss.com"
  onCallSupport:
    - 01XXXXXXXXXX
    - 01XXXXXXXXXX