build:
  version: "2.0"

cards:
  message: "Welcome to MssBank cards related QA APIs "
  contactDetails:
    name: "Adu - QA Lead"
    email: "adu@mss.com"
  onCallSupport:
    - 01XXXXXXXXXXX
    - 01XXXXXXXXXXX