build:
  version: "2.0"

loans:
  message: "Welcome to MssBank loans related QA APIs "
  contactDetails:
    name: "Bari - QA Lead"
    email: "bari@mss.com"
  onCallSupport:
    - 01XXXXXXXXXXX
    - 01XXXXXXXXXXX