build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related local APIs "
  contactDetails:
    name: "Tanver - Developer"
    email: "tanver@mss.com"
  onCallSupport:
    - 01XXXXXXXXXXX
    - 01XXXXXXXXXXX