spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to MSS Bank loans related prod APIs "
  contactDetails:
    name: "Aminul Bari - Product Owner"
    email: "aminul@mss.com"
  onCallSupport:
    - 01XXXXXXXXXXX
    - 01XXXXXXXYYYY