server:
  port: 8071
spring:
  application:
    name: "config-server"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # search-locations: "classpath:/config"    # using inside config server resource
          search-locations: "file:///home/tanver/Documents/Code/Microservices/NEW-Master-Microservices-with-Spring-Boot-Docker-Kubernetes/config"    # using file system