spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs "
  contactDetails:
    name: "Tanver - Developer"
    email: "tanver@mss.com"
  onCallSupport:
    - 01X28-XXXXXXXX
    - 01X66-XXXXXXXX